#!/bin/sh
# --- Copyright University of Sussex 1990.  All rights reserved. ---------
# File:            C.unix/lib/demo/mkall
# Purpose:         Make saved images for demonstration programs.
# Author:          Aaron Sloman (see revisions)
# Documentation:
# Related Files:   C.unix/lib/demo/mk*, C.vms/lib/demo/mkall.com

cd $usepop/pop/lib/demo

for f in mk*
do
    if [ $f != mkall ]
    then
        echo "Running $f"
        ./$f
    fi
done

# --- Revision History ---------------------------------------------------
# --- John Williams, Dec  6 1990
#       Re-written
# --- Aaron Sloman, Aug 15 1986
#       Fixed environment, and log printing
# --- Aaron Sloman, Apr 21 1986
#       Added mkms
