#!/bin/sh
# --- Copyright University of Sussex 1991.  All rights reserved. ---------
# File:             C.unix/lib/demo/mkms
# Purpose:          Make saved image with LIB * MSBLOCKS loaded
# Author:           Dave Hogg, May 26 1983 (see revisions)
# Documentation:    TEACH * MSBLOCKS  TEACH * MSDEMO
# Related Files:    LIB * MSBLOCKS, C.vms/lib/demo/msblocks.com


$popsys/pop11 %nort %noinit << \\\\

lib msblocks;

if syssave('$poplocalbin/msblocks.psv') then
    pr(popheader); pr(newline);
    false -> popheader;
    sysexit -> do_quit;
    go();
    sysexit();
endif;

sysexit();

\\

echo "mkms done"
rm -f $poplocalbin/msblocks.psv-


# --- Revision History ---------------------------------------------------
# --- Robert John Duncan, May 31 1991
#       Added %nort
# --- John Williams, Dec  6 1990
#       Now uses %noinit
# --- Aaron Sloman, Jan 27 1987
#       Restored to use msblocks
# --- Aaron Sloman, Jan 24 1987
#       Changed to use msdemo and make msdemo.psv
