#!/bin/sh
# --- Copyright University of Sussex 1991.  All rights reserved. ---------
# File:             C.unix/lib/demo/mkstroppy
# Purpose:          Create saved image for stroppy demo
# Author:           Aaron Sloman (see revisions)
# Documentation:
# Related Files:    LIB * STROPPY, C.vms/lib/demo/mkstroppy.com


$popsys/pop11 %nort %noinit << \\\\

lib stroppy;

if syssave('$poplocalbin/stroppy.psv') then

    define prmishap();
        pr('SORRY SOMETHING\'S GONE WRONG\n\nBYE\n');
        sysexit()
    enddefine;

    pr(popheader); pr(newline);
    false -> popheader;
    sysexit -> interrupt;
    false -> ranseed;
    pr('To interrupt, hold down the CTRL button and press the Y key\n');
    stroppy();
    sysexit()
endif;
sysexit();

\\

rm -f $poplocalbin/stroppy.psv-
echo "stroppy.psv done"


# --- Revision History ---------------------------------------------------
# --- Robert John Duncan, May 31 1991
#       Added %nort
# --- John Williams, Dec  6 1990
#       Now uses %noinit
# --- Aaron Sloman, Aug 15 1986
#       Fixed environment
